twitch:
  client_id: ${TWITCH_CLIENT_ID}
  client_secret: ${TWITCH_CLIENT_SECRET}

discord:
  system_webhook: ${DISCORD_WEBHOOK_SYSTEM}
  characters:
    "loop.trace": ${DISCORD_WEBHOOK_LOOP_TRACE}
    "packet.ghost": ${DISCORD_WEBHOOK_PACKET_GHOST}
    "[REDACTED]": ${DISCORD_WEBHOOK_REDACTED}
    "aux.proc": ${DISCORD_WEBHOOK_AUX_PROC}

defaults:
  announce_online: true
  announce_offline: false
  # system webhook for go-lives: do NOT set a default character
  template_online: |
    ðŸ”´ **{display_name} is LIVE**
    > {title}
    {url}

channels:
  - login: reburve
  - login: rubyhaven
  - login: mirasuriel
  - login: arthice
  - login: jadobe
  - login: jessabelle1998
  - login: reynysunset

#Discord comments settings

quotes:
enabled: true
quotes_dir: quotes
daily_min: 1
daily_max: 3
window_start: "10:00"
window_end: "21:00"
max_sentences: 3
max_chars: 350
no_links: true
no_mentions: true
files:
  "loop.trace": "loop.trace.txt"
  "packet.ghost": "packet.ghost.txt"
  "[REDACTED]": "redacted.txt"
  "aux.proc": "aux.proc.txt"

